# Generated by Django 5.0.6 on 2024-07-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_user_answer_alter_user_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="questions",
        ),
        migrations.AddField(
            model_name="user",
            name="question_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
